spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/user-service
    password: password
    username: username
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: emailNotification:com.jsl.user_management_service.service.notification.EmailNotification,examinationNotification:com.jsl.user_management_service.service.notification.ExaminationNotification,paymentNotification:com.jsl.user_management_service.service.notification.PaymentNotification

server:
  port: 8076

application:
  cors:
    origins: http://localhost:4200,http://localhost:8075
  security:
    jwt-secret-key: 6b1f2f5a661d9579c80a12a03cfb7d287fc2343d9a5824aa5822246594b1f585
    expiration: 86400000
    code-length: 6
  config:
    question-bank-url: http://localhost:8074/api/v1/questions # change this for gateway service
  user:
    registration-topic: user-registration
    exam-started-topic: exam-started-created
    exam-ended-topic: exam-ended-topic
    payment-confirmation-topic: payment-confirmation
  registration:
    notification:
      activation-url: http://localhost:4200/activate-account